spring.config.import: "configserver:http://localhost:8888"

spring:
  application:
    name: registry-service
  cloud:
    config:
      uri: http://localhost:8888
      username: root
      password: s3cr3t